name: Publish package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1

    - name: Install SDL dependencies
      # everything non-python from https://www.pygame.org/wiki/CompileUbuntu?parent=
      run: sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev build-essential

    - name: Install dependencies
      run: poetry install --no-root --no-interaction --without dev,examples

    - name: Configure Poetry for PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_PASSWORD }}

    - name: Publish to PyPI
      run: poetry publish --build -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}

    - name: Verify Package
      run: |
        pip install planning-library
