name: Style and typing checks

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install SDL dependencies
        # everything non-python from https://www.pygame.org/wiki/CompileUbuntu?parent=
        run: sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev build-essential

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Lint with ruff
        run: |
          poetry run ruff check --config pyproject.toml

      - name: Check formatting with ruff
        run: |
          poetry run ruff format --check --config pyproject.toml

      - name: Check types with mypy
        run: |
          poetry run mypy . --config-file pyproject.toml

      - name: Check types with pyright
        run: |
          poetry run pyright
